# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# The Authentication is via JWT. So you need a the private key of the certificate used.
- task: DownloadSecureFile@1
  name: key
  inputs:
    secureFile: 'server.key'
    retryCount: '5'
  
# Login to the target org
- script: sfdx force:auth:jwt:grant -u $(USERNAME) -i $(CONSUMER_ID) -r $(INSTANCE_URL)
  displayName: 'Authenticating'